--1
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT;

--2
SELECT DEPARTMENT_NAME || '         ' || CAPACITY|| ' Դϴ '
FROM TB_DEPARTMENT;

--3.
SELECT DEPARTMENT_NO
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '      а ';

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                        FROM TB_DEPARTMENT
                        WHERE DEPARTMENT_NAME = '      а ')
AND ABSENCE_YN = 'Y'
AND SUBSTR(STUDENT_SSN,8,1)='2';

--4.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO in ('A513079','A513090','A513091','A513110','A513119') 
ORDER BY STUDENT_NAME DESC;

--5.
SELECT DEPARTMENT_NAME,CATEGORY
FROM TB_DEPARTMENT
WHERE  CAPACITY >= '20'  AND CAPACITY <= '30'; 

--6.
select PROFESSOR_NAME
from TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                        FROM TB_DEPARTMENT
                        WHERE DEPARTMENT_NO IS NULL);
                        
--8.

SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;


--9.
SELECT CATEGORY
FROM TB_DEPARTMENT
GROUP BY CATEGORY
ORDER BY CATEGORY;

--10.
SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) = '2002' 
AND STUDENT_ADDRESS LIKE '%   ֽ %'
AND ABSENCE_YN = 'N';

--2-1 --DEPARTMENT_NO
SELECT *
FROM TB_CLASS; --CLASS_NO

SELECT *
FROM TB_STUDENT; --DEPARTMENT_NO

SELECT STUDENT_NO AS " й ",STUDENT_NAME AS " ̸ ",ENTRANCE_DATE AS "   г⵵"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 3;


--2-2
SELECT *
FROM TB_PROFESSOR;  --PROFESSOR_NAME

SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3; 

--2-3***
SELECT PROFESSOR_NAME ,FLOOR(FLOOR(SYSDATE-TO_DATE(SUBSTR(PROFESSOR_SSN,1,6)))/365)||'  ' AS "    "
FROM TB_PROFESSOR;

SELECT PROFESSOR_NAME,TO_DATE(SUBSTR(PROFESSOR_SSN,1,6))
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME = ' 峲  ';

--2-4
SELECT SUBSTR(PROFESSOR_NAME,2,2) AS " ̸ "
FROM TB_PROFESSOR;

--2-5          б               ڸ     Ϸ        .     ã Ƴ     ΰ ?  ̶ ,
--19  쿡      ϸ                                 .

SELECT *
FROM TB_STUDENT
WHERE SUBSTR(TO_CHAR(ADD_MONTHS(TO_DATE(SUBSTR(REPLACE(STUDENT_SSN, '-', ''),1,6),'RRMMDD'),(12*19))),1,2) < SUBSTR(TO_CHAR(ENTRANCE_DATE),1,2);

--2-6

--2020    ũ                     ΰ ?

SELECT  TO_CHAR(TO_DATE('20201225','YYYYMMDD'),'DAY')
FROM DUAL;

--2--7
/*TO_DATE('99/10/11','YY/MM/DD'), TO_DATE('49/10/11','YY/MM/DD') 
                             ǹ     ? 
   TO_DATE('99/10/11','RR/MM/DD'),TO_DATE('49/10/11','RR/MM/DD') 
                             ǹ     ?
*/
SELECT TO_DATE('99/10/11','YY/MM/DD'), TO_DATE('49/10/11','YY/MM/DD') 
FROM DUAL;
SELECT TO_DATE('99/10/11','RR/MM/DD'),TO_DATE('49/10/11','RR/MM/DD') 
FROM DUAL;
--2099/10/11 , 2049/10/11
--1999/10/11 , 2049/10/11


--2-8
/*         б    2000  ⵵           ڵ     й    A         ϰ   Ǿ  ִ . 2000  ⵵
      й          л       й     ̸         ִ  SQL         ۼ  Ͻÿ .
*/

SELECT STUDENT_NO,STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';


--2-9
/*
 й    A517178       Ƹ   л                      ϴ  SQL       ۼ  Ͻÿ .   ,
 ̶      ȭ           "    "  ̶           ϰ ,         ݿø  Ͽ   Ҽ           
 ڸ        ǥ      .
*/

SELECT  TRUNC(AVG(POINT),1) AS "    "
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

---2-10
/*
 а     л         Ͽ  " а   ȣ", " л   (  )"       ·                     
  µǵ     Ͻÿ .
*/

--1. а     ׷ ȭ

SELECT DEPARTMENT_NO 
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;
--2. ׷ ȭ    а       а   ȣ ,  л    


SELECT DEPARTMENT_NO AS " а   ȣ" ,COUNT(STUDENT_NAME) AS " л   "
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--2-11
--                           л                     Ǵ   ˾Ƴ    SQL     
-- ۼ  Ͻÿ .

SELECT COUNT(*) - COUNT(COACH_PROFESSOR_NO)
FROM  TB_STUDENT;

--2-12
/* й    A112113           л     ⵵              ϴ  SQL       ۼ  Ͻÿ .   ,
 ̶      ȭ           " ⵵", " ⵵        "  ̶           ϰ ,         ݿø  Ͽ 
 Ҽ             ڸ        ǥ   Ѵ */

SELECT SUBSTR(TERM_NO,1,4), ROUND (AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO ='A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
HAVING SUBSTR(TERM_NO,1,4) IN ('2001','2002','2003','2004')
ORDER BY SUBSTR(TERM_NO,1,4);


SELECT SUBSTR(TERM_NO,1,4) AS " ⵵" , POINT AS "           "
FROM TB_GRADE
GROUP BY TERM_NO
WHERE STUDENT_NO = 'A112113';

SELECT SUBSTR(TERM_NO,1,4)
FROM TB_GRADE
GROUP BY TERM_NO
WHERE STUDENT_NO = 'A112113';

SELECT SUBSTR(TERM_NO,1,4),POINT
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';


SELECT *
FROM (SELECT SUBSTR(TERM_NO,1,4) AS " ⵵" , POINT 
FROM TB_GRADE
GROUP BY " ⵵"
WHERE STUDENT_NO = 'A112113');


SELECT SUBSTR(TERM_NO,1,4), POINT
FROM TB_GRADE;

SELECT * 
FROM (SELECT SUBSTR(TERM_NO,1,4), POINT
FROM TB_GRADE)
WHERE  STUDENT_NO = 'A112113';


--2-13
/* а        л        ľ  ϰ        .  а    ȣ      л       ǥ   ϴ  SQL       
 ۼ  Ͻÿ .
*/

/*SELECT JOB_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY JOB_CODE
HAVING SUM(SALARY) >= 10000000;*/


SELECT DEPARTMENT_NO , COUNT(DECODE(ABSENCE_YN,'Y','Y'))
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

SELECT *
FROM TB_STUDENT




--2-14
SELECT STUDENT_NAME,COUNT(STUDENT_NAME)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) != 1
ORDER BY STUDENT_NAME;

--2-15
SELECT NVL(SUBSTR(TERM_NO,1,4),' '),NVL(SUBSTR(TERM_NO,5,2),' ') ,ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO ='A112113'
GROUP BY ROLLUP (SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2));



SELECT *
FROM TB_GRADE
WHERE STUDENT_NO ='A112113'
ORDER BY TERM_NO;


--3-1

SELECT STUDENT_NAME AS " л  ̸ " ,STUDENT_ADDRESS AS " ּ   "
FROM TB_STUDENT
ORDER BY STUDENT_NAME;


--3-2

SELECT STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;


--3-3

SELECT STUDENT_NAME AS " л  ̸ ",STUDENT_NO AS " й ",STUDENT_ADDRESS AS "       ּ "
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '%  ⵵%'
INTERSECT
SELECT STUDENT_NAME AS " л  ̸ ",STUDENT_NO AS " й ",STUDENT_ADDRESS AS "       ּ "
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) > 1899
AND EXTRACT(YEAR FROM ENTRANCE_DATE) < 2000;

SELECT ENTRANCE_DATE
FROM TB_STUDENT;


SELECT STUDENT_ADDRESS
FROM TB_STUDENT;


--3-4
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR P,TB_DEPARTMENT D
WHERE (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
AND P.DEPARTMENT_NO = 005
ORDER BY PROFESSOR_SSN ;


SELECT *
FROM TB_PROFESSOR;


SELECT *-- 005 DEPARTMENT_NO
FROM TB_DEPARTMENT;

--3-5
--학생 번호, 학생 이름, 학과 이름을 학생 이름으로 오름차순 정렬하여 출력하는 SQL
--문을 작성하시오.

SELECT STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME;

--3-6
SELECT CLASS_NAME, DEPARTMENT_NAME FROM TB_CLASS 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

--3-7
SELECT CLASS_NAME, PROFESSOR_NAME FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO);
--3-8 

SELECT TB_CLASS_PROFESSOR;
--3-9
SELECT CLASS_NAME, PROFESSOR_NAME FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR P USING(PROFESSOR_NO) 
JOIN TB_DEPARTMENT D ON(P.DEPARTMENT_NO = D.DEPARTMENT_NO)  
WHERE CATEGORY = '인문사회';

--3-10
SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "학생 이름", 
ROUND(AVG(POINT), 1) AS "전체 평점" FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
JOIN TB_GRADE USING(STUDENT_NO) 
WHERE DEPARTMENT_NAME = "음악학과"
GROUP BY STUDENT_NO, STUDENT_NAME ORDER BY STUDENT_NO;

--3-11
SELECT DEPARTMENT_NAME AS "학과이름", STUDENT_NAME AS "학생이름", 
PROFESSOR_NAME AS "지도교수이름" FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

--3-12
SELECT STUDENT_NAME, TERM_NO TERM_NAME FROM TB_STUDENT 
JOIN TB_GRADE USING(STUDENT_NO) 
JOIN TB_CLASS USING(CLASS_NO) 
WHERE TERM_NO LIKE '2007%' AND CLASS_NAME = '인간관계론';

--3-13
SELECT CLASS_NAME, DEPARTMENT_NAME FROM TB_CLASS 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO) 
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL;

--3-14

SELECT STUDENT_NAME AS "학생이름", NVL(PROFESSOR_NAME, '지도교수 미지정') AS "지도교수" FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
LEFT JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO) 
WHERE DEPARTMENT_NAME = '서반아어학과' ORDER BY STUDENT_NO;

--3-15
SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "이름", DEPARTMENT_NAME AS "학과 이름", 
ROUND(AVG(POINT), 8) AS "평점" 
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N' 
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME 
HAVING ROUND(AVG(POINT), 8) >= 4.0 ORDER BY STUDENT_NO;


--3-16
SELECT CLASS_NO, CLASS_NAME, ROUND(AVG(POINT), 8) "AVG(POINT)" FROM TB_CLASS 
JOIN TB_GRADE USING(CLASS_NO) 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
WHERE DEPARTMENT_NAME = '환경조경학과' AND CLASS_TYPE LIKE '전공%' 
GROUP BY CLASS_NO, CLASS_NAME ORDER BY CLASS_NO;


--3--17
SELECT STUDENT_NAME, STUDENT_ADDRESS FROM TB_STUDENT 
WHERE DEPARTMENT_NO = (
            SELECT DEPARTMENT_NO FROM TB_STUDENT 
            WHERE STUDENT_NAME = '최경희');

--3-18
SELECT STUDENT_NO, STUDENT_NAME FROM (
    SELECT STUDENT_NO, STUDENT_NAME FROM TB_STUDENT 
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
    JOIN TB_GRADE USING(STUDENT_NO) 
    WHERE DEPARTMENT_NAME = '국어국문학과' 
    GROUP BY STUDENT_NO, STUDENT_NAME 
    ORDER BY AVG(POINT) DESC)
WHERE ROWNUM = 1;

--3-19
SELECT DEPARTMENT_NAME AS "계열 학과명", 
ROUND(AVG(POINT), 1) AS "전공평점" 
FROM TB_DEPARTMENT 
JOIN TB_CLASS USING(DEPARTMENT_NO) 
JOIN TB_GRADE USING(CLASS_NO) 
WHERE CATEGORY = (
    SELECT CATEGORY FROM TB_DEPARTMENT 
    WHERE DEPARTMENT_NAME = '환경조경학과')
AND CLASS_TYPE LIKE '전공%' 
GROUP BY DEPARTMENT_NAME ORDER BY DEPARTMENT_NAME;