SELECT 
     NOTICE_NO
   , NOTICE_TITLE
   , USER_ID
   , COUNT
   , CREATE_DATE
  FROM NOTICE N
JOIN MEMBER ON (NOTICE_WRITER = USER_NO)
WHERE N.STATUS = 'Y'
ORDER
    BY NOTICE_NO DESC;
    


SELECT ROWNUM * A
FROM (SELECT 
     BOARD_NO
    ,CATEGORY_NAME
    ,BOARD_TITLE
    ,USER_ID
    ,COUNT
    ,CREATE_DATE
FROM BOARD B
JOIN CATEGORY USING(CATEGORY_NO)
JOIN MEMBER ON (BOARD_WRITER = USER_NO)
WHERE BOARD_TYPE = 1
AND B.STATUS = 'Y'
ORDER BY BOARD_NO DESC) A
WHERE ROWNUM BETWEEN 1 AND 30;


SELECT 
COUNT(*) count
FROM BOARD
WHERE BOARD_TYPE = 1
AND STATUS = 'Y';

SELECT 
     BOARD_NO
    ,CATEGORY_NAME
    ,BOARD_TITLE
    ,USER_ID
    ,COUNT
    ,CREATE_DATE
FROM BOARD B
JOIN CATEGORY USING(CATEGORY_NO)
JOIN MEMBER ON (BOARD_WRITER = USER_NO)
WHERE BOARD_TYPE = 1
AND B.STATUS = 'Y'
AND ROWNUM BETWEEN 1 AND 30
ORDER BY BOARD_NO DESC;




