--TEST
--1)
CREATE TABLE TB_CATRGORY(
    NAME VARCHAR2(10),
    USE_YN VARCHAR2(1) DEFAULT 'Y'
);
SELECT * FROM TB_CATRGORY;


--2)
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR(5) PRIMARY KEY,
    NAME VARCHAR(10)
);

SELECT * FROM TB_CLASS_TYPE;

--3)
ALTER TABLE TB_CATRGORY ADD PRIMARY KEY(NAME);

--4)
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;