--TEST
--1)
CREATE TABLE TB_CATRGORY(
    NAME VARCHAR2(10),
    USE_YN VARCHAR2(1) DEFAULT 'Y'
);
SELECT * FROM TB_CATRGORY;


--2)
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR(5) PRIMARY KEY,
    NAME VARCHAR(10)
);

SELECT * FROM TB_CLASS_TYPE;

--3)
ALTER TABLE TB_CATRGORY ADD PRIMARY KEY(NAME);

--4)
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

--5)
ALTER TABLE TB_CLASS_TYPE 
MODIFY NO VARCHAR(10)
MODIFY NAME VARCHAR(20); 

--6)
ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CLASS_TYPE_NO;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO CLASS_TYPE_NAME;

--7)

ALTER TABLE TB_CATRGORY
RENAME CONSTRAINT SYS_C007230 TO PK_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME CONSTRAINT SYS_C007229 TO PK_NO;

--8)
ALTER TABLE TB_CATRGORY MODIFY NAME VARCHAR(13);

INSERT INTO TB_CATRGORY VALUES ('공학','Y');
INSERT INTO TB_CATRGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATRGORY VALUES ('의학','Y');
INSERT INTO TB_CATRGORY VALUES ('예체능','Y');
INSERT INTO TB_CATRGORY VALUES ('인문사회','Y');
COMMIT;

SELECT * FROM TB_CATRGORY;

--9)
ALTER TABLE TB_DEPARTMENT ADD FOREIGN KEY (CATEGORY) REFERENCES TB_CATRGORY(NAME);
