/*
<트리거연습>
 내가 지정한 테이블이 DML문에 의해 변경사항이 생길 때 
(테이블 이벤트가 발생했을 떄 )


탈퇴회원 관리 테이블
가입번호
유저 아이디 주키 -UNIQUE/NOT NULL
유저 패스워드
유저 이름
유저 주민번호
유저 폰번호
유저 이메일
성별
가입일
*/
--1)회원정보 테이블 생성
CREATE TABLE Profile(
    PRO_NO NUMBER DEFAULT 1,
    USER_ID VARCHAR2(30) PRIMARY KEY,
    USER_PS VARCHAR2(120) NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL, 
    USER_NO VARCHAR2(9) UNIQUE NOT NULL,
    PHONE VARCHAR2(15) DEFAULT NULL,
    EMAIL VARCHAR2(30) DEFAULT NULL,
    GENDER CHAR(1) CHECK(GENDER IN ('M','F'))
);

   COMMENT ON COLUMN  PROFILE.PRO_NO IS '가입번호';
   COMMENT ON COLUMN  PROFILE.USER_ID IS '유저아이디';
   COMMENT ON COLUMN  PROFILE.USER_PS IS '유저패스워드';
   COMMENT ON COLUMN  PROFILE.USER_NAME IS '이름';
   COMMENT ON COLUMN  PROFILE.USER_NO IS '주민번호';
   COMMENT ON COLUMN  PROFILE.PHONE IS '핸드폰번호';
   COMMENT ON COLUMN  PROFILE.EMAIL IS '이메일';
   COMMENT ON COLUMN  PROFILE.GENDER IS '성별 M/F';
   COMMENT ON COLUMN  PROFILE.JOIN_DATE IS '가입일';
   

SELECT * FROM PROFILE;

ALTER TABLE PROFILE ADD JOIN_DATE DATE DEFAULT SYSDATE NOT NULL;


--2)탈퇴를 희망하는 회원정보 관리 테이블 생성 
-- 회원정보 테이블과는 다르게 트리거를 사용하기 위해 탈퇴여부확인하는 컬럼이 필요하다 STATUS 
CREATE TABLE DELUSER(
PRO_NO NUMBER DEFAULT 1,
    USER_ID VARCHAR2(30) PRIMARY KEY,
    USER_PS VARCHAR2(120) NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL, 
    USER_NO VARCHAR2(9) UNIQUE NOT NULL,
    PHONE VARCHAR2(15) DEFAULT NULL,
    EMAIL VARCHAR2(30) DEFAULT NULL,
    GENDER CHAR(1) CHECK(GENDER IN ('M','F')),
    STATUS CHAR(1) CHECK(STATUS IN('I'/'D')) NOT NULL
);

SELECT * FROM DELUSER;

COMMIT;
