----서브쿼리 문제
SELECT *
FROM EMPLOYEE; --DEPT_CODE, JOB_CODE
SELECT *
FROM DEPARTMENT; --DEPT_ID 
SELECT *
FROM JOB; --JOB_CODE

--1.
SELECT EMP_NAME , EMP_NO, DEPT_TITLE , JOB_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT ON (DEPT_ID  = DEPT_CODE)
JOIN JOB J ON (E.JOB_CODE = J. JOB_CODE)
WHERE SUBSTR(EMP_NO,1,2) >= '70' 
AND SUBSTR(EMP_NO,1,2) < '79'
AND SUBSTR(EMP_NAME,1,1) = '전';

--2.
SELECT EMP_ID,EMP_NAME,DEPT_TITLE , JOB_NAME
FROM EMPLOYEE E ,DEPARTMENT ,JOB J 
WHERE DEPT_ID = DEPT_CODE
AND E.JOB_CODE = J.JOB_CODE
AND EMP_NO = (SELECT MAX(EMP_NO)
FROM EMPLOYEE);


SELECT MAX(EMP_NO)
FROM EMPLOYEE;

--3.
SELECT EMP_ID,EMP_NAME,JOB_NAME
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE EMP_NAME LIKE '%형%';

--4.
SELECT EMP_NAME,DEPT_CODE
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D5','D6');

SELECT EMP_NAME,JOB_NAME,DEPT_CODE,DEPT_TITLE
FROM EMPLOYEE E,DEPARTMENT,JOB J
WHERE DEPT_CODE  (SELECT DEPT_CODE
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D5','D6'))
AND (DEPT_CODE = DEPT_ID)
AND (E.JOB_CODE=J.JOB_CODE);


