--1
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT;

--2
SELECT DEPARTMENT_NAME || '의 정원은' || CAPACITY|| '입니다'
FROM TB_DEPARTMENT;

--3.
SELECT DEPARTMENT_NO
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '국어국문학과';

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                        FROM TB_DEPARTMENT
                        WHERE DEPARTMENT_NAME = '국어국문학과')
AND ABSENCE_YN = 'Y'
AND SUBSTR(STUDENT_SSN,8,1)='2';

--4.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO in ('A513079','A513090','A513091','A513110','A513119') 
ORDER BY STUDENT_NAME DESC;

--5.
SELECT DEPARTMENT_NAME,CATEGORY
FROM TB_DEPARTMENT
WHERE  CAPACITY >= '20'  AND CAPACITY <= '30'; 

--6.
select PROFESSOR_NAME
from TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                        FROM TB_DEPARTMENT
                        WHERE DEPARTMENT_NO IS NULL);
                        
--8.

SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;


--9.
SELECT CATEGORY
FROM TB_DEPARTMENT
GROUP BY CATEGORY
ORDER BY CATEGORY;

--10.
SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) = '2002' 
AND STUDENT_ADDRESS LIKE '%전주시%'
AND ABSENCE_YN = 'N';

--2-1 --DEPARTMENT_NO
SELECT *
FROM TB_CLASS; --CLASS_NO

SELECT *
FROM TB_STUDENT; --DEPARTMENT_NO

SELECT STUDENT_NO AS "학번",STUDENT_NAME AS "이름",ENTRANCE_DATE AS "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 3;


--2-2
SELECT *
FROM TB_PROFESSOR;  --PROFESSOR_NAME

SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3; 

--2-3***
SELECT PROFESSOR_NAME ,FLOOR(FLOOR(SYSDATE-TO_DATE(SUBSTR(PROFESSOR_SSN,1,6)))/365)||'살' AS "나이"
FROM TB_PROFESSOR;

SELECT PROFESSOR_NAME,TO_DATE(SUBSTR(PROFESSOR_SSN,1,6))
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME = '장남희';

--2-4
SELECT SUBSTR(PROFESSOR_NAME,2,2) AS "이름"
FROM TB_PROFESSOR;

--2-5

