--1
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT;

--2
SELECT DEPARTMENT_NAME || '의 정원은' || CAPACITY|| '입니다'
FROM TB_DEPARTMENT;

--3.
SELECT DEPARTMENT_NO
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '국어국문학과';

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                        FROM TB_DEPARTMENT
                        WHERE DEPARTMENT_NAME = '국어국문학과')
AND ABSENCE_YN = 'Y'
AND SUBSTR(STUDENT_SSN,8,1)='2';

--4.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO in ('A513079','A513090','A513091','A513110','A513119') 
ORDER BY STUDENT_NAME DESC;

--5.
SELECT DEPARTMENT_NAME,CATEGORY
FROM TB_DEPARTMENT
WHERE  CAPACITY >= '20'  AND CAPACITY <= '30'; 


