
create table EMP(
    DEPT VARCHAR2(5),
    SALARY NUMBER,
    EMPNAME VARCHAR2(15)
);
INSERT INTO EMP VALUES ('D1',1500000,'È«±æµ¿');
INSERT INTO EMP VALUES ('D2',1600000,'È«±æ¼ø');
INSERT INTO EMP VALUES ('D3',1800000,'È«±æ¿ø');
INSERT INTO EMP VALUES ('D4',3500000,'È«±æÄ¡');
INSERT INTO EMP VALUES ('D5',2800000,'È«±æÆÈ');
INSERT INTO EMP VALUES ('D1',1100000,'È«±æ±¸');
INSERT INTO EMP VALUES ('D2',900000,'È«±æÀÏ');
INSERT INTO EMP VALUES ('D3',1200000,'È«±æÀÌ');
INSERT INTO EMP VALUES ('D4',1500000,'È«±æ»ï');
INSERT INTO EMP VALUES ('D5',1200000,'È«±æ»ç');
INSERT INTO EMP VALUES ('D4',6000000,'È«±æ½É');
INSERT INTO EMP VALUES ('D3',9000000,'±¸±æÀÌ');

SELECT  EMPNAME, SALARY
FROM EMP;


SELECT DEPT, SUM(SALARY) ÇÕ°è, FLOOR(AVG(SALARY)) Æò±Õ, COUNT(*) ÀÎ¿ø¼ö
FROM EMP
HAVING FLOOR(AVG(SALARY)) > 2800000
GROUP BY DEPT
ORDER BY DEPT ASC;

SELECT ROWNUM, EMPNAME, SALARY
FROM EMP
WHERE ROWNUM <= 3
ORDER BY SALARY DESC;


SELECT EMPNAME, SALARY
FROM EMP
ORDER BY SALARY DESC;

SELECT ROWNUM, EMPNAME, SALARY
FROM(SELECT EMPNAME, SALARY
FROM EMP
ORDER BY SALARY DESC)
WHERE ROWNUM <= 3;