INSERT INTO MEMBER VALUES(SEQ_USERNO.NEXTVAL,'XXX','XXX','XXX','X',XX,'XXX','XX','XX','XX',SYSDATE);
INSERT INTO MEMBER VALUES(SEQ_USERNO.NEXTVAL,'1', '1', '1', 'M', 1, 'eses@asdas', '01091288727', 'adada', '¾ø¾î', SYSDATE);



SELECT * FROM MEMBER;

select * FROM MEMBER WHERE USERNAME = '';

DELETE FROM MEMBER
WHERE USERNAME = '';