---1
INSERT INTO TB_CLASS_TYPE VALUES ('01','전공필수');
INSERT INTO TB_CLASS_TYPE VALUES ('02','전공선택');
INSERT INTO TB_CLASS_TYPE VALUES ('03','교양필수');
INSERT INTO TB_CLASS_TYPE VALUES ('04','교양선택');
INSERT INTO TB_CLASS_TYPE VALUES ('05','논문지도');
ROLLBACK;
SELECT * FROM TB_CLASS_TYPE;

---2.

CREATE TABLE  TB_STDF
AS (SELECT STUDENT_NO AS "학번",STUDENT_NAME AS "학생이름",STUDENT_ADDRESS AS "주소"
FROM TB_STUDENT
);

SELECT STUDENT_NO AS "학번",STUDENT_NAME AS "학생이름",STUDENT_ADDRESS AS "주소"
FROM TB_STUDENT;

SELECT * FROM TB_STDF;
DROP TABLE TB_STDF;

--답 시작
CREATE TABLE TB_KOCLASS
AS (SELECT STUDENT_NO AS "학번",
STUDENT_NAME AS "학생이름",
TO_CHAR(EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,2), 'RR'))) AS "출생년도",
PROFESSOR_NAME AS "교수이름"
FROM TB_STUDENT S
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과');
--답 끝

SELECT STUDENT_NO AS "학번",
STUDENT_NAME AS "학생이름",
TO_CHAR(EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,2), 'RR'))) AS "출생년도",
PROFESSOR_NAME AS "교수이름"
FROM TB_STUDENT S
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과';

SELECT * FROM TB_KOCLASS;

--4

SELECT * FROM TB_DEPARTMENT;

--답
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND((CAPACITY*1.1),-1);

--5
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

SELECT * FROM TB_STUDENT
WHERE STUDENT_NO = 'A413042';

--6

UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN,1,6);

SELECT * FROM TB_STUDENT;

--7
SELECT DEPARTMENT_NO
FROM TB_DEPARTMENT
where DEPARTMENT_NAME = '의학과'; --DEPAR NO 053 , 의학과


SELECT  *
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO = 053 AND STUDENT_NAME = '김명훈'; -- STU NO A331101

SELECT *
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE TERM_NO = 200501 AND STUDENT_NO = 'A331101'
;

UPDATE TB_GRADE
SET POINT = 3.5
WHERE STUDENT_NO = 'A331101' AND TERM_NO = 200501;

--8 성적 테이블(TB_GRADE) 에서 휴학생들의 성적항목을 제거하시오.
SELECT *
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE ABSENCE_YN = 'Y';

SELECT STUDENT_NO
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y';

UPDATE TB_GRADE
SET POINT = NULL
WHERE STUDENT_NO IN (SELECT STUDENT_NO
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y');


